sources:
  - name: my_source
    database: skiddo
    schema: dbt_obanahene
    config:
      enabled: true
    tables:
      - name: bike # enabled

      - name: customer #  enabled
       